//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeadChildren
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfDeath { get; set; }
        public int Age { get; set; }
        public long GuildId { get; set; }
    
        public virtual DiscordGuild DiscordGuild { get; set; }
    }
}
