//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscordGuild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscordGuild()
        {
            this.BugReports = new HashSet<BugReport>();
            this.DeadChildrens = new HashSet<DeadChildren>();
            this.DiscordChannels = new HashSet<DiscordChannel>();
        }
    
        public long GuildId { get; set; }
        public string GuildPrefix { get; set; }
        public Nullable<long> GuildWelcome { get; set; }
        public Nullable<long> GuildLeave { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BugReport> BugReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeadChildren> DeadChildrens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiscordChannel> DiscordChannels { get; set; }
        public virtual DiscordChannel DiscordChannel { get; set; }
        public virtual DiscordChannel DiscordChannel1 { get; set; }
    }
}
