//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FishType()
        {
            this.UserFishInventories = new HashSet<UserFishInventory>();
            this.UserFishLogs = new HashSet<UserFishLog>();
        }
    
        public int FishId { get; set; }
        public string FishName { get; set; }
        public string FishMessage { get; set; }
        public long FIshWorth { get; set; }
        public bool FishActive { get; set; }
        public string FishEmoji { get; set; }
        public int FishRarity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFishInventory> UserFishInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFishLog> UserFishLogs { get; set; }
    }
}
