//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileBackground
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProfileBackground()
        {
            this.Users = new HashSet<User>();
            this.UserBackgrounds = new HashSet<UserBackground>();
        }
    
        public int BackgroundId { get; set; }
        public long BackgroundPrice { get; set; }
        public string BackgroundDir { get; set; }
        public bool BackgroundActive { get; set; }
        public string Category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBackground> UserBackgrounds { get; set; }
    }
}
