//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpamTrack
    {
        public long UserId { get; set; }
        public long GuildId { get; set; }
        public double Pressure { get; set; }
        public long LastMessage { get; set; }
    }
}
