//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFishInventory
    {
        public long UserId { get; set; }
        public int FishId { get; set; }
        public int Amount { get; set; }
        public int AmountSold { get; set; }
        public int LogId { get; set; }
    
        public virtual FishType FishType { get; set; }
        public virtual UserEconomy UserEconomy { get; set; }
    }
}
