//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBackground
    {
        public long UserId { get; set; }
        public int BackgroundId { get; set; }
        public int RowID { get; set; }
    
        public virtual ProfileBackground ProfileBackground { get; set; }
        public virtual User User { get; set; }
    }
}
