//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSlotLog
    {
        public int SlotId { get; set; }
        public long UserId { get; set; }
        public long SlotAward { get; set; }
        public System.DateTime DateUsed { get; set; }
        public Nullable<long> MoneyBefore { get; set; }
        public Nullable<long> MoneyAfter { get; set; }
    
        public virtual UserEconomy UserEconomy { get; set; }
    }
}
