//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFishLog
    {
        public int FishLogId { get; set; }
        public long UserId { get; set; }
        public int FishId { get; set; }
        public System.DateTime DateFished { get; set; }
        public Nullable<long> MoneyBefore { get; set; }
        public Nullable<long> MoneyAfter { get; set; }
    
        public virtual FishType FishType { get; set; }
        public virtual UserEconomy UserEconomy { get; set; }
    }
}
