//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeBot.Helper.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BugReports = new HashSet<BugReport>();
            this.UserBackgrounds = new HashSet<UserBackground>();
        }
    
        public long UserId { get; set; }
        public int UserXp { get; set; }
        public long TotalXp { get; set; }
        public int UserLevel { get; set; }
        public bool UserAdmin { get; set; }
        public int BackgroundId { get; set; }
        public string ColorHex { get; set; }
        public bool Restricted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BugReport> BugReports { get; set; }
        public virtual OsuUser OsuUser { get; set; }
        public virtual ProfileBackground ProfileBackground { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBackground> UserBackgrounds { get; set; }
        public virtual UserEconomy UserEconomy { get; set; }
    }
}
